# -*- coding: utf-8 -*-
"""
Created on Sat Oct 17 09:22:24 2020

@author: tjcombs

The data is from the following source:
    
https://www.kaggle.com/anikannal/solar-power-generation-data

"""

import pandas as pd

def get_generation_data():
    '''
    Returns a DataFrame of the solar power generation data.

    DATE_TIME: Date and time for each observation. Observations recorded at 15 
    minute intervals.
        
    PLANT_ID:
        PLANT_ID = 4135001 ==> PLANT = 1
        PLANT_ID = 4136001 ==> PLANT = 2
        
    SOURCE_KEY: The inverter id.
    
    DC_POWER: Amount of DC power generated by the inverter (source_key) in this 
    15 minute interval. Units - kW.
    
    AC_POWER: Amount of AC power generated by the inverter (source_key) in this 
    15 minute interval. Units - kW.
    
    DAILY_YIELD: Daily yield is a cumulative sum of power generated on that 
    day, till that point in time.
    
    TOTAL_YIELD: This is the total yield for the inverter till that point in 
    time.
    
    '''
    plant1_generation = pd.read_csv('archive/Plant_1_Generation_Data.csv')
    plant1_generation['DATE_TIME'] = pd.to_datetime(plant1_generation['DATE_TIME'])
    plant2_generation = pd.read_csv('archive/Plant_2_Generation_Data.csv')
    plant2_generation['DATE_TIME'] = pd.to_datetime(plant2_generation['DATE_TIME'])
    # The two data sets have the same columns
    assert(set(plant1_generation) == set(plant2_generation))
    # Combine datasets
    generation = pd.concat((plant1_generation, plant2_generation))
    return generation

def get_weather_data():
    '''
    Returns a DataFrame of the weather data.
    
    DATE_TIME: Date and time for each observation. Observations recorded at 
    15 minute intervals.
    
    PLANT_ID:
        PLANT_ID = 4135001 ==> PLANT = 1
        PLANT_ID = 4136001 ==> PLANT = 2
    
    SOURCE_KEY:
    Stands for the sensor panel id. This will be common for the entire file 
    because there's only one sensor panel for the plant.
    
    Since each plant has only one SOURCE_KEY, we don't need to keep the 
    SOURCE_KEY column and we can just use the PLANT_ID column in its place.
    
    AMBIENT_TEMPERATURE: This is the ambient temperature at the plant.
    
    MODULE_TEMPERATURE: There's a module (solar panel) attached to the sensor 
    panel. This is the temperature reading for that module.
    
    IRRADIATION: Amount of irradiation for the 15 minute interval.
    '''
    
    plant1_weather = pd.read_csv('archive/Plant_1_Weather_Sensor_Data.csv')
    plant2_weather = pd.read_csv('archive/Plant_2_Weather_Sensor_Data.csv')
    # The two data sets have the same columns
    assert(set(plant1_weather)==set(plant2_weather))
    # Combine data sets
    weather = pd.concat((plant1_weather, plant2_weather))
    
    return weather

if __name__ == '__main__':
    generation = get_generation_data()
    weather = get_weather_data()
    